const sampleEmails = [
  {
    name: "High risk banking alert",
    expected: "phishing",
    sender: "security@bankofamerica-verify.com",
    replyTo: "claims-team@fastmail-login.net",
    returnPath: "bounce@bankofamerica-verify.com",
    claimedBrand: "Bank of America",
    spf: "fail",
    dkim: "fail",
    dmarc: "fail",
    receivedHops: 1,
    subject: "URGENT: account locked, verify immediately",
    body: "Dear customer, your account has been locked due to suspicious activity. You must verify your username, password, and card number within 30 minutes or your online banking access will be suspended. Click http://bankofamerica-secure-login.example.ru/verify now."
  },
  {
    name: "Legitimate meeting update",
    expected: "legitimate",
    sender: "noreply@university.edu",
    replyTo: "noreply@university.edu",
    returnPath: "noreply@university.edu",
    claimedBrand: "University",
    spf: "pass",
    dkim: "pass",
    dmarc: "pass",
    receivedHops: 3,
    subject: "Network defense class room change",
    body: "Hello students, tomorrow's network defense session has moved to room B204. No action is required. The updated schedule is available on the official student portal."
  },
  {
    name: "Password reset lure",
    expected: "phishing",
    sender: "support@microsoft-security-center.co",
    replyTo: "it-helpdesk@outlook-reset.net",
    returnPath: "mailer@outlook-reset.net",
    claimedBrand: "Microsoft",
    spf: "softfail",
    dkim: "fail",
    dmarc: "fail",
    receivedHops: 2,
    subject: "Password reset required today",
    body: "We detected unauthorized login attempts on your Microsoft account. Confirm your password at https://bit.ly/secure-m365-check to prevent termination of your mailbox."
  },
  {
    name: "Internal IT maintenance",
    expected: "legitimate",
    sender: "it.helpdesk@company.com",
    replyTo: "it.helpdesk@company.com",
    returnPath: "it.helpdesk@company.com",
    claimedBrand: "Company IT",
    spf: "pass",
    dkim: "pass",
    dmarc: "pass",
    receivedHops: 4,
    subject: "Scheduled VPN maintenance",
    body: "The VPN service will be unavailable from 22:00 to 23:00 for scheduled maintenance. You do not need to send credentials or take any action."
  },
  {
    name: "Prize fraud",
    expected: "phishing",
    sender: "winner@promo-rewards.xyz",
    replyTo: "agent-prize@temporarymail.com",
    returnPath: "bounce@promo-rewards.xyz",
    claimedBrand: "Amazon",
    spf: "fail",
    dkim: "unknown",
    dmarc: "fail",
    receivedHops: 1,
    subject: "Congratulations, claim your reward",
    body: "You have been selected for an exclusive Amazon reward. Send your full name, address, phone number, and payment details to release the prize before midnight."
  },
  {
    name: "Invoice notification",
    expected: "legitimate",
    sender: "billing@cloudvendor.com",
    replyTo: "billing@cloudvendor.com",
    returnPath: "billing@cloudvendor.com",
    claimedBrand: "CloudVendor",
    spf: "pass",
    dkim: "pass",
    dmarc: "pass",
    receivedHops: 5,
    subject: "Monthly invoice available",
    body: "Your monthly invoice is available in the billing dashboard. Sign in through the normal company portal if you want to review it."
  },
  {
    name: "Executive wire transfer request",
    expected: "phishing",
    sender: "ceo.company@gmail.com",
    replyTo: "ceo.company@gmail.com",
    returnPath: "ceo.company@gmail.com",
    claimedBrand: "Human Resources",
    spf: "pass",
    dkim: "pass",
    dmarc: "unknown",
    receivedHops: 2,
    subject: "Need this paid today",
    body: "I am in a meeting and need you to process a wire transfer before close of business. Do not call me. Reply when you can receive the bank details."
  },
  {
    name: "GitHub security notice",
    expected: "legitimate",
    sender: "noreply@github.com",
    replyTo: "noreply@github.com",
    returnPath: "noreply@github.com",
    claimedBrand: "GitHub",
    spf: "pass",
    dkim: "pass",
    dmarc: "pass",
    receivedHops: 4,
    subject: "Security alert: new SSH key added",
    body: "A new SSH key was added to your account. If this was you, no action is required. Review your account settings by visiting GitHub directly in your browser."
  },
  {
    name: "QR phishing mailbox warning",
    expected: "phishing",
    sender: "admin@microsoft-mailbox-support.click",
    replyTo: "helpdesk@microsoft-mailbox-support.click",
    returnPath: "bounce@microsoft-mailbox-support.click",
    claimedBrand: "Microsoft",
    spf: "fail",
    dkim: "unknown",
    dmarc: "fail",
    receivedHops: 0,
    subject: "Mailbox storage full",
    body: "Your mailbox will be closed today. Scan the QR code in the attachment and login with your work password to keep access."
  },
  {
    name: "HR policy update",
    expected: "legitimate",
    sender: "hr@company.com",
    replyTo: "hr@company.com",
    returnPath: "hr@company.com",
    claimedBrand: "Human Resources",
    spf: "pass",
    dkim: "pass",
    dmarc: "pass",
    receivedHops: 3,
    subject: "Updated remote work policy",
    body: "The remote work policy has been updated. Please read the policy in the company intranet when you have time. No form submission is required."
  },
  {
    name: "Legitimate password policy reminder",
    expected: "legitimate",
    sender: "security@company.com",
    replyTo: "security@company.com",
    returnPath: "security@company.com",
    claimedBrand: "Company IT",
    spf: "pass",
    dkim: "pass",
    dmarc: "pass",
    receivedHops: 3,
    subject: "Password policy reminder",
    body: "Today we are reminding everyone that IT will never ask for your password by email. Use the normal company portal when your scheduled password rotation is due."
  },
  {
    name: "IP address login page",
    expected: "phishing",
    sender: "support@paypal.com",
    replyTo: "support@paypal.com",
    returnPath: "bounce@mailer-paypal.com",
    claimedBrand: "PayPal",
    spf: "softfail",
    dkim: "fail",
    dmarc: "fail",
    receivedHops: 2,
    subject: "Confirm your login",
    body: "We detected suspicious activity. Confirm your password now at http://185.12.44.8/paypal/login before your account is locked."
  },
  {
    name: "Lookalike subdomain lure",
    expected: "phishing",
    sender: "alerts@google.com.secure-login.account-reset.top",
    replyTo: "alerts@google.com.secure-login.account-reset.top",
    returnPath: "bounce@google.com.secure-login.account-reset.top",
    claimedBrand: "Google",
    spf: "fail",
    dkim: "fail",
    dmarc: "fail",
    receivedHops: 1,
    subject: "Final warning for account recovery",
    body: "Dear user, your Google access will be suspended. Login at https://google.com.secure-login.account-reset.top/recovery to verify your account."
  }
];
